name: main

on:
  schedule:
    - cron: '0-30/27 8-17 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current time
        run: date > current_time.txt

      - name: Add current time to README
        run: |
          echo "Current Time: $(cat current_time.txt)" >> README.md
          git config --local user.name "gaoyundl1"
          git config --local user.email "10017116@qq.com"
          git add README.md
          git commit -m "Update README with current time"
          git push
