# 这是一个github action的配置文件，用于调用AI语言模型，生成一段笑话，并写入到README.md文件中
# 代码的逻辑是：
# 1. 每分钟触发一次workflow，使用ChatGLM-2模型生成一段笑话
# 2. 将当前的日期和时间，格式是YYYY-MM-DD HH:MM，和生成的笑话写入到README.md文件的开头，用换行符分隔

name: Joke Generator # workflow的名字
on:
  schedule:
    - cron: '* * * * *' # 每分钟触发一次
jobs:
  joke: # 任务的名字
    runs-on: ubuntu-latest # 运行的环境
    steps:
      - name: Checkout # 拉取代码
        uses: actions/checkout@v3
      - name: Generate Joke # 生成笑话
        id: joke # 任务的id，用于后面引用
        run: | # 运行的命令
          # 调用ChatGLM-2模型，生成一段笑话，保存到变量joke中
          # 这里使用了curl命令，假设ChatGLM-2模型有一个公开的API接口，可以通过POST请求获取生成的内容
          # API接口的地址是https://chatglm-2.com/api/generate，请求的参数是{"prompt": "Tell me a joke"}
          # 响应的内容是一个JSON字符串，包含一个key为"joke"的字段，值为生成的笑话
          joke=$(curl -X POST https://chatglm-2.com/api/generate -d '{"prompt": "Tell me a joke"}' | jq -r '.joke')
          # 将变量joke的值输出到标准输出，用于打印和后面引用
          echo "::set-output name=joke::$joke"
      - name: Write to README.md # 写入到README.md文件中
        run: | # 运行的命令
          # 获取当前的日期和时间，格式是YYYY-MM-DD HH:MM，保存到变量datetime中
          datetime=$(date +"%Y-%m-%d %H:%M")
          # 将当前时间和生成的笑话写入到README.md文件的开头，用换行符分隔
          echo -e "$datetime\n${{ steps.joke.outputs.joke }}\n\n$(cat README.md)" > README.md
          # 将修改后的文件提交到github仓库中，使用actions用户和邮箱，提交信息为"Update README.md"
          git config --local user.email "10017116@qq.com"
          git config --local user.name "gaoyundl1"
          git add README.md
          git commit -m "Update README.md"
          git push
