on:
  schedule:
    - cron: '* */10 * * *'  # every ten minutes, starting at the top of the hour

jobs:
  log_date:
    runs-on: ubuntu-latest
    steps:
      - name: Record Current Date
        run: |
          date=$(date '+%Y%m%d')
          touch "$date.txt"
          echo "$date" >> "$date.txt"
      - name: Record Current Time
        run: |
          sleep $(( (RANDOM % 1800) + 1200 ))
          echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$date.txt"
