name: main

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  generate_log:
    runs-on: ubuntu-latest
    steps:
      - name: Generate log file
        run: |
          date=$(date '+%Y%m%d')
          touch "$date.txt"
          echo "$date" >> "$date.txt"
      - name: Add current time to log file
        id: add_time
        run: |
          while true; do
            sleep ${{ random.int(1200, 1800) }} # sleep for 20-30 minutes (in seconds)
            echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$date.txt"
          done
