name: main

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  generate_log:
    runs-on: ubuntu-latest
    steps:
      - name: Generate log file
        run: |
          date=$(date '+%Y%m%d')
          touch "$date.txt"
          echo "$date" >> "$date.txt"
      - name: Add current time to log file
        id: add_time
        run: |
          while true; do
            sleep=$(( (RANDOM % 1800) + 1200 )) # generate random number between 1200 and 1800
            sleep $sleep
            echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$date.txt"
          done
